on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: oracle-actions/setup-java@v1
        with:
          release: 17

      - run: |
          javac -d out Foo.java
          jar --create --file foo.jar -C out .
          jar --validate --file foo.jar
